window.MyDiaper = window.MyDiaper || {};

(function(){
  const app = document.getElementById('app');
  const modalRoot = document.getElementById('modalRoot');
  const toastRoot = document.getElementById('toastRoot');
  const ui = { route:'today', offerMode:'local', marketFilter:'Alle', marketQuery:'', marketOnlyMine:false, offerView:'map', activityRange:'day', mapLocation:null };
  const repository = MyDiaper.repository;
  const family = MyDiaper.createFamilyContext(repository, MyDiaper.store);
  const pricing = MyDiaper.domain.pricing;
  const {icon,art,rainbow} = MyDiaper.visuals;

  const esc = (v='') => String(v).replace(/[&<>'"]/g, ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[ch]));
  const activeChild = family.activeChild;
  const recommendSize = weight => MyDiaper.domain.sizes.recommendSize(weight, MyDiaper.catalog.sizeGuide);
  const bestOfferForSize = size => MyDiaper.offerService.search({scope:'local',size})[0] || MyDiaper.offerService.search({scope:'local'})[0];
  const unitPriceText = offer => { const value = pricing.offerUnitPrice(offer); return value === null ? '–' : value.toFixed(2).replace('.',','); };
  const productValue=(form,data)=>typeof form.querySelector==='function'?MyDiaper.productFields.value(form):{productSizeId:undefined,productPackageId:null,packageUnits:null,brand:data.get('brand'),line:data.get('line'),size:data.get('size')};
  const offerCard = (o,mode)=> `<article class="card offer-card"><div class="product-thumb">🛍️</div><div><div class="flex" style="gap:7px"><strong>${esc(o.store)}</strong>${o.oldPrice?`<span class="badge danger">-${Math.round((1-o.price/o.oldPrice)*100)}%</span>`:''}</div><div>${esc(o.product)} · Größe ${esc(o.size)}</div><div class="muted">${o.count} Stück · ${unitPriceText(o)} € / Windel${mode==='local'?` · ${o.distance} km`:o.shipping?` · ${esc(o.shipping)}`:''}</div></div><div class="price">${o.price.toFixed(2).replace('.',',')} €<small>${o.oldPrice?o.oldPrice.toFixed(2).replace('.',',')+' € vorher':'Testangebot'}</small></div></article>`;
  const childSwitcher = ()=> `<div class="child-switcher">${repository.listChildren().map(child=>family.childView(child.id)).map(c=>`<button class="child-chip ${c.id===activeChild().id?'active':''}" data-action="switch-child" data-id="${esc(c.id)}"><span class="avatar ${esc(c.color)}">${esc(c.name.slice(0,1).toUpperCase())}</span><strong>${esc(c.name)}</strong><small>Größe ${esc(c.currentSize)}</small></button>`).join('')}</div>`;
  const screenHeader=(title,back='today',action='')=>`<header class="screen-header"><button class="icon-btn" data-action="route" data-route="${back}" aria-label="Zurück">${icon('back')}</button><h1>${esc(title)}</h1>${action?`<button class="icon-btn" data-action="${action}" aria-label="Angebote suchen">${icon('search')}</button>`:'<span></span>'}</header>`;
  const greeting=()=>{const value=MyDiaper.store.get().settings.salutation||{};return value.choice==='mama'?'Hallo Mama!':value.choice==='papa'?'Hallo Papa!':value.choice==='custom'&&value.customName?`Hallo ${value.customName}!`:value.choice==='none'?'Willkommen!':'Hallo!';};
  const inventoryForChild=childId=>MyDiaper.domain.inventory.forChild(MyDiaper.store.get().inventoryLots,childId);
  const ctx = {ui,esc,...family,recommendSize,bestOfferForSize,offerCard,childSwitcher,compareOffers:pricing.compareOffers,icon,art,rainbow,screenHeader,greeting,inventoryForChild};

  function render(){
    const fn = MyDiaper.features[ui.route] || MyDiaper.features.today;
    app.innerHTML = fn(ctx);
    document.getElementById('appShell').dataset.screen=ui.route;
    document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active', b.dataset.route===ui.route));
    const state=MyDiaper.store.get(),child=activeChild(),stockDue=MyDiaper.domain.reminders.stockDue(child.days,state.settings.reminders.stock,state.settings.reminderConfig);
    document.getElementById('notificationDot').classList.toggle('hidden', !stockDue);
    MyDiaper.productFields?.enhance(app);
    if(ui.route==='offers'&&ui.offerMode!=='online'&&ui.offerView==='map'){
      const offers=MyDiaper.offerService.search({scope:'local',query:(ui.offerSearch||'').trim()});
      MyDiaper.offerMap?.mount(document.getElementById('offerMap'),offers,ui.highlightOffer,id=>{ui.highlightOffer=id;render();},ui.mapLocation);
    }else MyDiaper.offerMap?.destroy();
    app.focus({preventScroll:true});
  }
  function toast(msg){
    const d=document.createElement('div'); d.className='toast'; d.textContent=msg; d.role='status'; toastRoot.appendChild(d); setTimeout(()=>d.remove(),2600);
  }
  let modalReturnFocus=null,modalScrollY=0,modalInitial='',modalDismissible=true;
  const isModalOpen=()=>String(modalRoot.className||'').includes('open');
  const formState=()=>typeof modalRoot.querySelectorAll==='function'?[...modalRoot.querySelectorAll('input,select,textarea')].map(input=>`${input.name||input.id}:${input.type==='checkbox'||input.type==='radio'?input.checked:input.value}`).join('|'):'';
  function lockPage(){modalScrollY=window.scrollY||0;if(!document.body)return;document.body.classList.add('modal-open');document.body.style.top=`-${modalScrollY}px`;}
  function unlockPage(){if(document.body){document.body.classList.remove('modal-open');document.body.style.top='';}window.scrollTo({top:modalScrollY,left:0,behavior:'instant'});}
  function closeModal(force=false){if(!isModalOpen())return true;if(!force&&modalInitial&&formState()!==modalInitial&&!confirm('Ungespeicherte Änderungen verwerfen?'))return false;modalRoot.className='modal-root';modalRoot.innerHTML='';unlockPage();if(modalReturnFocus&&typeof modalReturnFocus.focus==='function')modalReturnFocus.focus();modalReturnFocus=null;modalInitial='';return true;}
  function modal(title,body,options={}){if(isModalOpen())closeModal(true);modalReturnFocus=document.activeElement||null;modalDismissible=options.dismissible!==false;lockPage();modalRoot.className='modal-root open'; modalRoot.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><span class="modal-grabber"></span><div class="modal-header"><h2>${esc(title)}</h2>${modalDismissible?`<button class="icon-btn" data-action="close-modal" aria-label="Dialog schließen">${icon('close')}</button>`:'<span></span>'}</div>${body}</div>`;MyDiaper.productFields?.enhance(modalRoot);setTimeout(()=>{modalInitial=formState();const target=modalRoot.querySelector&&modalRoot.querySelector('input, select, textarea, button');if(target&&typeof target.focus==='function')target.focus();},0); }
  const dateText=value=>value?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(value)):'ohne Datum';
  function showNotifications(){ const c=activeChild(),state=MyDiaper.store.get(),due=MyDiaper.domain.reminders.stockDue(c.days,state.settings.reminders.stock,state.settings.reminderConfig); modal('Benachrichtigungen', `<div class="stack"><div class="card soft"><strong>Vorrat ${due?'wird knapp':'in Ordnung'}</strong><div class="muted">${esc(c.name)}: ${c.stock} Stück · ca. ${family.daysText(c)} Tage · Grenze ${state.settings.reminderConfig.stockDays} Tage</div></div><div class="card soft"><strong>Größe regelmäßig prüfen</strong><div class="muted">Aktueller Gewichts-Richtwert: Größe ${recommendSize(c.weight)} · Intervall ${state.settings.reminderConfig.sizeCheckWeeks} Wochen</div></div></div>`); }

  function childForm(child){
    const c=child ? family.childView(child.id) : {name:'',birthdate:'',weight:6,height:60,color:'mint',currentBrand:'Pampers',currentLine:'Premium Protection',currentSize:'3',dailyUse:6,stock:0,types:['Windel']};
    modal(child?'Kinderprofil bearbeiten':'Neues Kinderprofil', `<form id="childForm" class="stack" data-id="${esc(c.id||'')}">
      <div class="form-grid"><div class="input-group"><label>Name / Spitzname</label><input class="input" name="name" value="${esc(c.name)}" required></div><div class="input-group"><label>Geburtsdatum</label><input class="input" type="date" name="birthdate" value="${esc(c.birthdate)}"></div><div class="input-group"><label>Gewicht in kg</label><input class="input" type="number" step="0.1" min="1" max="80" name="weight" value="${c.weight}" required></div><div class="input-group"><label>Größe in cm</label><input class="input" type="number" min="30" max="200" name="height" value="${c.height}" required></div></div>
      <fieldset class="profile-color-picker"><legend>Profilfarbe</legend><div class="profile-color-options">${MyDiaper.profileColors.map(option=>`<label class="profile-color-choice"><input type="radio" name="color" value="${esc(option.id)}" ${c.color===option.id?'checked':''}><span class="color-swatch ${esc(option.id)}" aria-hidden="true"></span><span>${esc(option.label)}</span></label>`).join('')}</div><small>Frei wählbar und nicht an ein Geschlecht gekoppelt.</small></fieldset>
      <div class="form-grid"><div class="input-group"><label>Aktuelle Marke</label><select class="select" name="brand">${[...new Set([c.currentBrand,...MyDiaper.catalog.brands.map(b=>b.name)])].map(name=>`<option ${name===c.currentBrand?'selected':''}>${esc(name)}</option>`).join('')}</select></div><div class="input-group"><label>Aktuelle Größe</label><input class="input" name="size" value="${esc(c.currentSize)}" required></div><div class="input-group"><label>Verbrauch pro Tag</label><input class="input" type="number" min="0" step="0.1" max="20" name="dailyUse" value="${c.dailyUse}" required></div><div class="input-group"><label>Vorrat</label><input class="input" type="number" min="0" name="stock" value="${c.stock}" required></div></div>
      <div class="input-group"><label>Windelarten (Komma getrennt)</label><input class="input" name="types" value="${esc(c.types.join(', '))}"></div>
      <button class="btn primary block">Speichern</button></form>`);
  }

  function fitCheck(){
    const c=activeChild();
    modal(`Fit-Check für ${c.name}`, `<form id="fitForm" class="stack form-sheet" data-child-id="${esc(c.id)}" data-set-id="${esc(c.setId)}"><div class="modal-context">${icon('diaper')}<div><strong>${esc(c.setLabel)}</strong><small>${esc(c.currentBrand)} ${esc(c.currentLine)} · Größe ${esc(c.currentSize)}</small></div></div>
      <div class="question-block"><strong>Läuft die Windel häufiger aus?</strong><div class="choice-grid"><label class="choice"><input type="radio" name="leak" value="yes" required> Ja, häufiger</label><label class="choice"><input type="radio" name="leak" value="no"> Nein</label></div></div>
      <div class="question-block"><strong>Gibt es deutliche Abdrücke?</strong><div class="choice-grid"><label class="choice"><input type="radio" name="marks" value="yes" required> Ja</label><label class="choice"><input type="radio" name="marks" value="no"> Nein</label></div></div>
      <div class="question-block"><strong>Wie schließen die Klett-/Seitenbereiche?</strong><div class="choice-grid"><label class="choice"><input type="radio" name="closure" value="tight" required> Eher knapp</label><label class="choice"><input type="radio" name="closure" value="good"> Gut</label></div></div>
      <div class="question-block"><strong>Probleme hauptsächlich nachts?</strong><div class="choice-grid"><label class="choice"><input type="radio" name="night" value="yes" required> Ja</label><label class="choice"><input type="radio" name="night" value="no"> Nein</label></div></div>
      <button class="btn primary block">Auswertung speichern</button></form>`);
  }

  function experienceModal(experience){
    const c=activeChild(),rating=(name,label,low,high)=>`<fieldset class="rating-field"><legend>${label}</legend><div class="rating-scale">${[1,2,3,4,5].map(value=>`<label><input type="radio" name="${name}" value="${value}" ${(experience?.[name]??3)===value?'checked':''} required><span>${value}</span></label>`).join('')}</div><div class="rating-ends"><small>${low}</small><small>${high}</small></div></fieldset>`;
    modal(experience?'Erfahrung bearbeiten':'Erfahrung eintragen',`<form id="experienceForm" class="stack form-sheet" data-child-id="${esc(c.id)}" data-set-id="${esc(c.setId)}" data-id="${esc(experience?.id||'')}"><div class="modal-context mint">${icon('heart')}<div><strong>${esc(c.name)} · ${esc(c.setLabel)}</strong><small>${esc(c.currentBrand)} ${esc(c.currentLine)} · Größe ${esc(c.currentSize)}</small></div></div><p class="form-explainer">Diese Einschätzung gilt nur für dieses Kind und dieses Windelset.</p>
      ${rating('fitRating','Passform','schwierig','sehr gut')}${rating('leakRating','Auslaufschutz','schwach','sehr gut')}${rating('nightRating','Nachtleistung','ungeeignet','sehr gut')}${rating('skinComfortRating','Hautkomfort','schwach','sehr gut')}${rating('priceValueRating','Preis-Leistung','schwach','sehr gut')}
      <div class="input-group"><label for="sizeTendency">Wie fällt die Größe aus?</label><select class="select" id="sizeTendency" name="sizeTendency"><option value="small" ${experience?.sizeTendency==='small'?'selected':''}>Eher klein</option><option value="normal" ${!experience||experience.sizeTendency==='normal'?'selected':''}>Größenentsprechend</option><option value="large" ${experience?.sizeTendency==='large'?'selected':''}>Eher groß</option></select></div>
      <label class="avoid-check"><input type="checkbox" name="avoidRecommendation" ${experience?.avoidRecommendation?'checked':''}><span>${icon('shield')}</span><span><strong>Nicht erneut empfehlen</strong><small>Dieses Produkt bei Vorschlägen für ${esc(c.name)} zurückstellen.</small></span></label>
      <fieldset class="question-block"><strong>Würdet ihr dieses Produkt wieder kaufen?</strong><div class="choice-grid"><label class="choice"><input type="radio" name="wouldBuyAgain" value="yes" ${experience?.wouldBuyAgain===true?'checked':''} required> Ja</label><label class="choice"><input type="radio" name="wouldBuyAgain" value="no" ${experience?.wouldBuyAgain===false?'checked':''}> Nein</label></div></fieldset>
      <div class="input-group"><label for="experienceNotes">Persönliche Notiz</label><textarea class="input" id="experienceNotes" name="notes" maxlength="600" rows="3" placeholder="Was ist euch aufgefallen?">${esc(experience?.notes||'')}</textarea></div>
      <button class="btn primary block">Erfahrung speichern</button>${experience?'<button class="btn danger block" type="button" data-action="experience-delete">Erfahrung löschen</button>':''}</form>`);
  }

  function historyModal(){
    const c=activeChild(),fits=repository.listFitChecks(c.id,c.setId).slice().reverse(),experiences=repository.listExperiences(c.id,c.setId).slice().reverse(),sizes=repository.listSizeHistory(c.id,c.setId).slice().reverse();
    const experienceCards=experiences.map(item=>`<article class="history-card"><span class="history-icon mint">${icon('heart')}</span><div><strong>Produkterfahrung · ${dateText(item.updatedAt||item.createdAt)}</strong><p>${esc(item.notes||({small:'Fällt eher klein aus.',normal:'Wirkt größenentsprechend.',large:'Fällt eher groß aus.'}[item.sizeTendency]||'Bewertung gespeichert.'))}</p><small>${item.avoidRecommendation?'Nicht erneut empfehlen':'Persönliche Bewertung für dieses Set'}</small></div><button class="icon-btn" data-action="experience-edit" data-id="${esc(item.id)}" aria-label="Erfahrung bearbeiten">${icon('user')}</button></article>`).join('');
    const fitCards=fits.map(item=>`<article class="history-card"><span class="history-icon blue">${icon('check')}</span><div><strong>${esc(item.result)}</strong><p>${esc(item.note)}</p><small>Fit-Check · ${dateText(item.createdAt)}</small></div></article>`).join('');
    const sizeCards=sizes.map(item=>{const changedSize=item.fromSize!==item.toSize,from=[item.fromProduct?.brand,item.fromProduct?.line].filter(Boolean).join(' '),to=[item.toProduct?.brand,item.toProduct?.line].filter(Boolean).join(' ');return `<article class="history-card"><span class="history-icon peach">${icon('arrow')}</span><div><strong>${item.fromSize==null?`Start mit Größe ${esc(item.toSize)}`:changedSize?`Größe ${esc(item.fromSize)} → ${esc(item.toSize)}`:'Produkt gewechselt'}</strong><p>${from&&to&&from!==to?`${esc(from)} → ${esc(to)}`:item.reason==='catalog'?'Aus dem Testkatalog übernommen':item.reason==='profile'?'Über das Kinderprofil geändert':item.reason==='manual'?'Im Windelset geändert':'Ausgangsprodukt übernommen'}</p><small>Produkt- & Größenverlauf · ${dateText(item.createdAt)}</small></div></article>`;}).join('');
    modal(`Verlauf für ${c.name}`,`<div class="modal-context">${icon('clock')}<div><strong>${esc(c.setLabel)}</strong><small>${esc(c.currentBrand)} ${esc(c.currentLine)} · Größe ${esc(c.currentSize)}</small></div></div><div class="history-list">${experienceCards}${fitCards}${sizeCards}${!experienceCards&&!fitCards&&!sizeCards?'<div class="friendly-empty compact"><strong>Noch kein Verlauf</strong><p>Fit-Checks, Erfahrungen und Größenwechsel erscheinen später hier.</p></div>':''}</div><button class="btn primary block" data-action="experience-add">Neue Erfahrung eintragen</button>`);
  }

  function stockModal(){ const c=activeChild(),set=repository.listSets(c.id,true).find(item=>item.id===c.setId); modal('Windelset bearbeiten', `<form id="stockForm" class="stack" data-child-id="${esc(c.id)}" data-set-id="${esc(c.setId)}"><div class="inline-note">${esc(c.name)} · ${esc(c.setLabel)}</div>${MyDiaper.productFields.html({...set,purpose:set.purpose,productSizeId:set.productSizeId})}<div class="input-group"><label for="setStock">Gesamter aktueller Bestand</label><input id="setStock" class="input" type="number" min="0" name="stock" value="${c.stock}" required></div><div class="input-group"><label for="setDailyUse">Ø Verbrauch pro Tag</label><input id="setDailyUse" class="input" type="number" min="0" step="0.1" max="20" name="dailyUse" value="${c.dailyUse}" required></div><div class="inline-note">Ein Produktwechsel ändert bestehende Vorratsposten nicht rückwirkend.</div><button class="btn primary block">Speichern</button></form>`); }
  function locationField(value='Zuhause'){const presets=['Zuhause','Wickeltasche','Kita','Bei Familie'];return `<div class="input-group"><label for="storageLocation">Lagerort</label><input class="input" id="storageLocation" name="storageLocation" list="storageLocations" maxlength="80" value="${esc(value)}" required><datalist id="storageLocations">${presets.map(item=>`<option value="${item}">`).join('')}</datalist></div>`;}
  function addStockModal(){ const c=activeChild(),set=repository.listSets(c.id,true).find(item=>item.id===c.setId),day=new Date().toISOString().slice(0,10);modal('Packung / Stück hinzufügen', `<form id="addStockForm" class="stack" data-child-id="${esc(c.id)}" data-set-id="${esc(c.setId)}">${MyDiaper.productFields.html({...set,purpose:set.purpose,productSizeId:set.productSizeId,includePackage:true})}<div class="form-grid"><div class="input-group"><label for="stockAmount">Anzahl hinzufügen</label><input id="stockAmount" class="input" name="amount" type="number" min="1" value="30" required></div><div class="input-group"><label for="stockDate">Kauf-/Eingangsdatum</label><input id="stockDate" class="input" name="acquiredAt" type="date" value="${day}"></div></div>${locationField()}<div class="input-group"><label for="stockNote">Notiz (optional)</label><input id="stockNote" class="input" name="note" maxlength="240" placeholder="z. B. Packung aus dm"></div><div class="inline-note">Dieser Posten bleibt eindeutig ${esc(c.name)}, ${esc(c.setLabel)}, dem Produkt und Lagerort zugeordnet.</div><button class="btn primary block">Zum Vorrat hinzufügen</button></form>`); }
  function setFormModal(existing){
    const c=activeChild(),set=existing||{label:'Windel',brand:'',line:'',size:c.currentSize,dailyUse:0},stock=existing?repository.viewChild(c.id,existing.id).stock:0;
    modal(existing?'Windelset bearbeiten':'Windelset hinzufügen',`<form id="setForm" class="stack" data-child-id="${esc(c.id)}" data-id="${esc(existing?.id||'')}"><div class="input-group"><label for="setLabel">1. Windelart</label><select class="select" id="setLabel" name="label">${['Windel','Pants','Nachtwindel','Schwimmwindel'].map(label=>`<option ${label===set.label?'selected':''}>${label}</option>`).join('')}</select></div>${MyDiaper.productFields.html({...set,purpose:MyDiaper.domain.model.purpose(set.label),productSizeId:set.productSizeId})}<div class="input-group"><label for="manageSetUse">Verbrauch / Tag</label><input class="input" id="manageSetUse" name="dailyUse" type="number" min="0" max="20" step="0.1" value="${set.dailyUse}" required></div>${existing?'':`<div class="input-group"><label for="manageSetStock">Startbestand</label><input class="input" id="manageSetStock" name="stock" type="number" min="0" value="${stock}" required></div>`}<button class="btn primary block">Set speichern</button></form>`);
  }
  function manageSetsModal(){
    const c=activeChild(),sets=repository.listSets(c.id,true);
    modal(`Windelsets für ${c.name}`,`<div class="history-list">${sets.map(set=>`<article class="history-card ${set.active?'':'is-inactive'}"><span class="history-icon ${set.active?'mint':'peach'}">${icon(set.purpose==='night'?'clock':set.purpose==='swim'?'drop':set.purpose==='pants'?'swap':'diaper')}</span><div><strong>${esc(set.label)}${set.isPrimary?' · Hauptset':''}</strong><p>${esc(set.brand)} ${esc(set.line)} · Größe ${esc(set.size)}</p><small>${set.active?'Aktiv':'Pausiert'} · Ø ${set.dailyUse}/Tag</small></div><div class="row-actions"><button class="icon-btn" data-action="edit-set" data-id="${esc(set.id)}" aria-label="${esc(set.label)} bearbeiten">${icon('user')}</button>${set.active&&!set.isPrimary?`<button class="icon-btn" data-action="set-primary" data-id="${esc(set.id)}" aria-label="Als Hauptset verwenden">${icon('check')}</button>`:''}<button class="icon-btn" data-action="toggle-set" data-id="${esc(set.id)}" data-active="${set.active}" aria-label="${set.active?'Pausieren':'Aktivieren'}">${icon('swap')}</button><button class="icon-btn" data-action="delete-set" data-id="${esc(set.id)}" aria-label="Set löschen">${icon('close')}</button></div></article>`).join('')}</div><button class="btn primary block" data-action="new-set">${icon('plus')} Weiteres Set hinzufügen</button>`);
  }
  function lotFormModal(lot){
    const c=activeChild(),date=String(lot.acquiredAt||'').slice(0,10);
    modal('Vorratsposten bearbeiten',`<form id="lotForm" class="stack" data-child-id="${esc(c.id)}" data-set-id="${esc(c.setId)}" data-id="${esc(lot.id)}"><div class="form-grid"><div class="input-group"><label for="lotInitial">Ursprünglich</label><input class="input" id="lotInitial" name="initialUnits" type="number" min="0" value="${lot.initialUnits}" required></div><div class="input-group"><label for="lotRemaining">Noch vorhanden</label><input class="input" id="lotRemaining" name="remainingUnits" type="number" min="0" value="${lot.remainingUnits}" required></div><div class="input-group"><label for="lotDate">Datum</label><input class="input" id="lotDate" name="acquiredAt" type="date" value="${esc(date)}"></div></div>${locationField(lot.storageLocation)}<div class="input-group"><label for="lotNote">Notiz</label><input class="input" id="lotNote" name="note" maxlength="240" value="${esc(lot.note||'')}"></div><button class="btn primary block">Vorratsposten speichern</button></form>`);
  }
  function manageLotsModal(){
    const c=activeChild(),lots=repository.listLots(c.id,c.setId);
    modal(`Vorrat · ${c.setLabel}`,`<div class="history-list">${lots.length?lots.map(lot=>{const product=lot.productSizeId?MyDiaper.domain.catalog.details(MyDiaper.productCatalog,lot.productSizeId):null;return `<article class="history-card"><span class="history-icon blue">${icon('box')}</span><div><strong>${lot.remainingUnits} von ${lot.initialUnits} Stück · ${esc(lot.storageLocation)}</strong><p>${product?`${esc(product.brand.name)} ${esc(product.product.name)} · Größe ${esc(product.size.label)}`:esc(lot.note||'Manuelles Produkt')}</p><small>${dateText(lot.acquiredAt||lot.createdAt)} · ${esc(lot.source||'manuell')}</small></div><div class="row-actions"><button class="icon-btn" data-action="edit-lot" data-id="${esc(lot.id)}" aria-label="Vorratsposten bearbeiten">${icon('user')}</button><button class="icon-btn" data-action="delete-lot" data-id="${esc(lot.id)}" aria-label="Vorratsposten löschen">${icon('close')}</button></div></article>`;}).join(''):'<div class="friendly-empty compact"><strong>Noch keine Vorratsposten</strong><p>Füge eine Packung oder einzelne Windeln hinzu.</p></div>'}</div><button class="btn primary block" data-action="add-stock">${icon('plus')} Vorrat ergänzen</button>`);
  }
  function barcodeModal(value=''){
    const native=MyDiaper.platform.capabilities.status();
    modal('Barcode erkennen',`<form id="barcodeForm" class="stack"><div class="input-group"><label for="barcodeValue">EAN / GTIN</label><input class="input" id="barcodeValue" name="barcode" inputmode="numeric" autocomplete="off" value="${esc(value)}" placeholder="Ziffern des Barcodes" required></div>${native.barcode?`<button type="button" class="btn secondary block" data-action="barcode-scan">${icon('search')} Mit Kamera scannen</button>`:''}<div class="inline-note">Im Testkatalog sind bewusst noch keine ungeprüften EANs hinterlegt. Unbekannte Codes können als lokaler Korrekturentwurf erfasst werden.</div><button class="btn primary block">Code prüfen</button></form>`);
  }
  function barcodeResult(barcode){
    const found=MyDiaper.catalogCorrectionRepository.lookup(barcode),c=activeChild();
    if(found)return modal('Produkt erkannt',`<div class="modal-context mint">${icon('check')}<div><strong>${esc(found.brand.name)} ${esc(found.product.name)}</strong><small>Größe ${esc(found.size.label)} · ${found.pack.unitsPerPack} Stück</small></div></div><form id="barcodeStockForm" class="stack" data-child-id="${esc(c.id)}" data-set-id="${esc(c.setId)}" data-product-size-id="${esc(found.size.id)}" data-units="${found.pack.unitsPerPack}"><div class="inline-note">Das Produkt wird dem aktuell gewählten Set zugeordnet und als eigener Vorratsposten ergänzt.</div><button class="btn primary block">Übernehmen & Vorrat ergänzen</button></form>`);
    modal('Code noch unbekannt',`<div class="friendly-empty compact">${art('elephant')}<strong>Kein Katalogtreffer</strong><p>${esc(barcode)} ist lokal nicht zugeordnet.</p></div><form id="correctionForm" class="stack" data-barcode="${esc(barcode)}"><div class="input-group"><label for="correctionKind">Grund</label><select class="select" id="correctionKind" name="kind"><option value="unknown_barcode">Barcode fehlt im Katalog</option><option value="wrong_assignment">Falsche Zuordnung</option><option value="wrong_pack_size">Falsche Packungsgröße</option><option value="other">Sonstiges</option></select></div><div class="input-group"><label for="correctionNote">Hinweis</label><textarea class="input" id="correctionNote" name="note" minlength="3" maxlength="500" required placeholder="Welches Produkt und welche Packungsgröße steht auf der Packung?"></textarea></div><div class="inline-note">Nur lokaler Entwurf – ohne Backend wird nichts versendet.</div><button class="btn primary block">Entwurf speichern</button></form>`);
  }
  function correctionsModal(){const items=MyDiaper.catalogCorrectionRepository.list();modal('Produktkorrekturen',`<div class="history-list">${items.length?items.map(item=>`<article class="history-card"><span class="history-icon peach">${icon('search')}</span><div><strong>${esc(item.barcode)}</strong><p>${esc(item.note)}</p><small>Lokaler Entwurf · ${dateText(item.createdAt)}</small></div><button class="icon-btn" data-action="delete-correction" data-id="${esc(item.id)}" aria-label="Entwurf löschen">${icon('close')}</button></article>`).join(''):'<div class="friendly-empty compact"><strong>Keine Korrekturentwürfe</strong><p>Unbekannte oder fehlerhafte Produktcodes erscheinen hier.</p></div>'}</div><button class="btn primary block" data-action="barcode-entry">Barcode eingeben</button>`);}
  function locationModal(){ modal('Standort für Angebote', `<form id="locationForm" class="stack"><div class="input-group"><label>Ort oder PLZ</label><input class="input" name="location" value="${esc(MyDiaper.store.get().settings.location)}" required></div><button type="button" class="btn secondary block" data-action="use-current-location">${icon('pin')} Standort einmalig verwenden</button><div class="inline-note">Nur nach deinem Tippen. Die genaue Position wird nicht gespeichert und es gibt kein Hintergrund-Tracking.</div><button class="btn primary block">Ort / PLZ speichern</button></form>`); }
  function salutationModal(firstRun=false){const value=MyDiaper.store.get().settings.salutation||{};modal(firstRun?'Willkommen bei MyDiaper':'Begrüßung anpassen',`<form id="salutationForm" class="stack form-sheet"><div class="welcome-elephant">${art('elephant')}</div><p class="form-explainer">Wie möchtest du auf der Startseite angesprochen werden?</p><div class="salutation-options">${[['mama','Mama'],['papa','Papa'],['parent','Elternteil'],['custom','Name / Spitzname'],['none','Ohne persönliche Anrede']].map(([id,label])=>`<label class="choice"><input type="radio" name="choice" value="${id}" ${(value.choice||'parent')===id?'checked':''} required> ${label}</label>`).join('')}</div><div class="input-group"><label for="salutationName">Name / Spitzname (bei eigener Anrede)</label><input class="input" id="salutationName" name="customName" maxlength="60" value="${esc(value.customName||'')}" placeholder="z. B. Chris"></div><button class="btn primary block">Begrüßung speichern</button></form>`,{dismissible:!firstRun});}
  function activityModal(){const c=activeChild(),events=repository.listUsage(c.id),now=new Date(),from=ui.activityRange==='week'?new Date(now.getFullYear(),now.getMonth(),now.getDate()-6):new Date(now.getFullYear(),now.getMonth(),now.getDate()),summary=MyDiaper.domain.activity.summarize(events,{from}),visible=events.filter(item=>new Date(item.usedAt)>=from),label=item=>MyDiaper.domain.activity.labels[item.contents]||'Nicht erfasst';modal(`Windelwechsel · ${c.name}`,`<div class="tabs"><button class="tab ${ui.activityRange==='day'?'active':''}" data-action="activity-range" data-range="day">Heute</button><button class="tab ${ui.activityRange==='week'?'active':''}" data-action="activity-range" data-range="week">7 Tage</button></div><div class="activity-summary"><span><strong>${summary.changes}</strong><small>Wechsel</small></span><span><strong>${summary.wet}</strong><small>Nass</small></span><span><strong>${summary.stool}</strong><small>Stuhlgang</small></span></div><div class="history-list">${visible.length?visible.map(item=>{const set=repository.listSets(c.id,true).find(entry=>entry.id===item.setId);return `<article class="history-card"><span class="history-icon blue">${icon(item.contents==='stool'||item.contents==='both'?'heart':'drop')}</span><div><strong>${esc(label(item))}</strong><p>${esc(set?.label||'Windelset')} · ${new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(item.usedAt))}</p><small>${esc(item.note||'Lokal protokolliert')}</small></div><div class="row-actions"><button class="icon-btn" data-action="activity-edit" data-id="${esc(item.id)}" aria-label="Windelwechsel bearbeiten">${icon('user')}</button><button class="icon-btn" data-action="activity-undo" data-id="${esc(item.id)}" aria-label="Windelwechsel rückgängig">${icon('swap')}</button></div></article>`;}).join(''):'<div class="friendly-empty compact"><strong>Noch kein Wechsel erfasst</strong></div>'}</div><button class="btn primary block" data-action="activity-add">Windelwechsel eintragen</button>`);}
  function activityForm(event){const c=activeChild(),sets=repository.listSets(c.id),local=(value=>{const d=new Date(value||Date.now()),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,16);})(event?.usedAt);modal(event?'Windelwechsel bearbeiten':'Windelwechsel eintragen',`<form id="activityForm" class="stack" data-child-id="${esc(c.id)}" data-id="${esc(event?.id||'')}"><div class="input-group"><label for="activitySet">Windelset</label><select class="select" id="activitySet" name="setId" ${event?'disabled':''}>${sets.map(set=>`<option value="${esc(set.id)}" ${(event?.setId||c.setId)===set.id?'selected':''}>${esc(set.label)} · Größe ${esc(set.size)}</option>`).join('')}</select></div><fieldset class="question-block"><strong>Was wurde beobachtet?</strong><div class="activity-choices">${[['wet','Nur nass'],['stool','Nur Stuhlgang'],['both','Beides'],['dry','Trocken']].map(([id,label])=>`<label class="choice"><input type="radio" name="contents" value="${id}" ${(event?.contents||'wet')===id?'checked':''} required> ${label}</label>`).join('')}</div></fieldset><div class="input-group"><label for="activityTime">Zeitpunkt</label><input class="input" id="activityTime" name="usedAt" type="datetime-local" value="${local}" required></div><div class="input-group"><label for="activityNote">Notiz (optional)</label><input class="input" id="activityNote" name="note" maxlength="240" value="${esc(event?.note||'')}"></div><div class="inline-note">Lokale Alltagserfassung ohne medizinische Bewertung.</div><button class="btn primary block">${event?'Änderung speichern':'Wechsel speichern & 1 Windel abziehen'}</button></form>`);}
  function priceAlertModal(offer){
    if(!offer||!offer.productSizeId)throw new Error('Für dieses Angebot ist noch keine Produktgröße verknüpft.');
    const c=activeChild(),alerts=MyDiaper.offerRepository.listAlerts(c.id),candidates=alerts.filter(item=>item.productSizeId===offer.productSizeId&&(item.scope===offer.scope||item.scope==='both')),existing=candidates.find(item=>item.productPackageId===offer.productPackageId)||candidates.find(item=>!item.productPackageId);
    const unit=pricing.offerUnitPrice(offer),unitValue=existing?.maxUnitPrice??(unit===null?'':Math.ceil(unit*100)/100),packValue=existing?.maxPackPrice??'';
    modal(existing?'Preisalarm bearbeiten':'Preisalarm anlegen',`<form id="priceAlertForm" class="stack form-sheet" data-child-id="${esc(c.id)}" data-product-size-id="${esc(offer.productSizeId)}" data-product-package-id="${esc(offer.productPackageId||'')}" data-id="${esc(existing?.id||'')}"><div class="modal-context mint">${icon('bell')}<div><strong>${esc(c.name)} · ${esc(offer.product)}</strong><small>Größe ${esc(offer.size)} · aktuell ${unit===null?'–':unit.toFixed(2).replace('.',',')} € pro Windel</small></div></div><p class="form-explainer">Du kannst eine Stückpreisgrenze, eine Grenze für genau diese ${offer.counter||offer.count}-Stück-Packung oder beides verwenden.</p><div class="input-group"><label for="maxUnitPrice">Maximaler Stückpreis in Euro (optional)</label><input class="input" id="maxUnitPrice" name="maxUnitPrice" type="number" min="0.01" max="10" step="0.01" value="${unitValue===''?'':Number(unitValue).toFixed(2)}"></div><div class="input-group"><label for="maxPackPrice">Maximaler Packungspreis in Euro (optional)</label><input class="input" id="maxPackPrice" name="maxPackPrice" type="number" min="0.01" max="500" step="0.01" value="${packValue===''?'':Number(packValue).toFixed(2)}" ${offer.productPackageId?'':'disabled'}><small>${offer.productPackageId?`Gilt exakt für ${offer.count} Stück · entspricht bei der Grenze dem berechneten Stückpreis.`:'Für dieses Angebot fehlt eine eindeutige Packungs-ID.'}</small></div><div class="input-group"><label for="alertScope">Angebotsbereich</label><select class="select" id="alertScope" name="scope"><option value="local" ${(existing?.scope||offer.scope)==='local'?'selected':''}>Nur in deiner Nähe</option><option value="online" ${(existing?.scope||offer.scope)==='online'?'selected':''}>Nur online</option><option value="both" ${existing?.scope==='both'?'selected':''}>Lokal und online</option></select></div><div class="inline-note">Die Testversion speichert den Alarm lokal. Benachrichtigungen und echte Preisfeeds folgen später.</div><button class="btn primary block">Preisalarm speichern</button></form>`);
  }
  function manageAlertsModal(){
    const c=activeChild(),alerts=MyDiaper.offerRepository.listAlerts(c.id);
    modal(`Preisalarme für ${c.name}`,`<div class="history-list price-alert-list">${alerts.length?alerts.map(alert=>{const found=MyDiaper.domain.catalog.details(MyDiaper.productCatalog,alert.productSizeId),pack=alert.productPackageId?MyDiaper.domain.catalog.createIndex(MyDiaper.productCatalog).packages.get(alert.productPackageId):null,limits=[alert.maxUnitPrice!==null?`bis ${alert.maxUnitPrice.toFixed(2).replace('.',',')} € pro Windel`:'',alert.maxPackPrice!==null?`bis ${alert.maxPackPrice.toFixed(2).replace('.',',')} € für ${pack?.unitsPerPack||'diese'} Stück`:''].filter(Boolean).join(' · ');return `<article class="history-card"><span class="history-icon mint">${icon('bell')}</span><div><strong>${esc(found?`${found.brand.name} ${found.product.name}`:'Katalogprodukt')}</strong><p>Größe ${esc(found?.size.label||'–')} · ${esc(limits)}</p><small>${({local:'In deiner Nähe',online:'Online',both:'Lokal und online'})[alert.scope]}</small></div><button class="icon-btn" data-action="remove-price-alert" data-id="${esc(alert.id)}" aria-label="Preisalarm entfernen">${icon('close')}</button></article>`;}).join(''):'<div class="friendly-empty compact"><strong>Noch keine Preisalarme</strong><p>Öffne ein Angebot und lege dort deine persönliche Preisgrenze fest.</p></div>'}</div><p class="catalog-disclaimer">Demo-Angebote lösen keine echte Push-Nachricht aus.</p>`);
  }
  function offerSourcesModal(){
    const imports=MyDiaper.offerImportRepository.list(),status=MyDiaper.offerImportRepository.status(),template=MyDiaper.offerImportRepository.template();
    const sources=`<article class="source-card demo"><span>${icon('box')}</span><div><strong>Lokale MyDiaper-Testdaten</strong><small>Feste Demo-Quelle · nicht live geprüft</small></div><span></span></article>${imports.map(item=>`<article class="source-card"><span>${icon('check')}</span><div><strong>${esc(item.label)}</strong><small>${item.offerCount} Angebot${item.offerCount===1?'':'e'} · importiert am ${dateText(item.importedAt)}</small></div><button class="icon-btn" data-action="remove-offer-source" data-id="${esc(item.providerKey)}" aria-label="${esc(item.label)} entfernen">${icon('close')}</button></article>`).join('')}`;
    modal('Angebotsquellen',`<div class="source-list">${sources}</div>${status.warning?`<div class="inline-note">${esc(status.warning)}</div>${status.readOnly?'<button class="reset-link" data-action="reset-offer-imports">Beschädigte Importdaten zurücksetzen</button>':''}`:''}<form id="offerImportForm" class="stack form-sheet"><div class="input-group"><label for="offerImportFile">JSON-Datei auswählen</label><input class="input file-input" id="offerImportFile" type="file" accept="application/json,.json"></div><div class="input-group"><label for="offerImportBundle">oder Angebotsdaten einfügen</label><textarea class="input json-import" id="offerImportBundle" name="bundle" maxlength="${MyDiaper.domain.offers.MAX_IMPORT_CHARS}" placeholder="JSON-Angebotsdaten hier einfügen"></textarea></div><div class="privacy-note">${icon('shield')}<span>Der Import wird lokal gespeichert. Produktpackungen müssen bereits im internen Katalog existieren; Preise werden nicht als live verifiziert ausgegeben.</span></div><button class="btn primary block">Quelle prüfen & importieren</button></form><details class="source-help"><summary>Formatbeispiel anzeigen</summary><pre class="json-preview">${esc(template)}</pre></details>`);
  }
  function backupExportModal(){
    const text=MyDiaper.domain.backup.serialize(MyDiaper.store.get());
    modal('Familien-Backup exportieren',`<div class="privacy-note">${icon('shield')}<span>Das Backup enthält private Kinder-, Vorrats-, Fit- und Einstellungsdaten. Es wird nur lokal angezeigt oder heruntergeladen.</span></div><div class="input-group"><label for="familyBackupExport">Versioniertes JSON-Backup</label><textarea class="input json-import" id="familyBackupExport" readonly>${esc(text)}</textarea></div><div class="backup-actions"><button class="btn primary" data-action="download-family-backup">JSON herunterladen</button><button class="btn secondary" data-action="family-backup-import">Backup einlesen</button></div>`);
  }
  function backupImportModal(){
    modal('Familien-Backup einlesen',`<form id="backupImportForm" class="stack form-sheet"><div class="input-group"><label for="familyBackupFile">JSON-Datei auswählen</label><input class="input file-input" id="familyBackupFile" type="file" accept="application/json,.json"></div><div class="input-group"><label for="familyBackupText">oder Backup-Daten einfügen</label><textarea class="input json-import" id="familyBackupText" name="backup" maxlength="${MyDiaper.domain.backup.MAX_CHARS}" placeholder="MyDiaper-Familien-Backup hier einfügen" required></textarea></div><div class="privacy-note">${icon('shield')}<span>Vor dem Einlesen werden Format, Version und sämtliche Kind-/Set-Zuordnungen geprüft. Erst danach kannst du das Ersetzen bestätigen.</span></div><button class="btn primary block">Backup prüfen & einlesen</button></form>`);
  }
  function reminderSettingsModal(){const config=MyDiaper.store.get().settings.reminderConfig;modal('Erinnerungen fein einstellen',`<form id="reminderForm" class="stack"><div class="form-grid"><div class="input-group"><label for="stockDays">Vorratswarnung ab</label><input class="input" id="stockDays" name="stockDays" type="number" min="1" max="30" value="${config.stockDays}" required><small>Tagen Reichweite</small></div><div class="input-group"><label for="sizeWeeks">Größencheck alle</label><input class="input" id="sizeWeeks" name="sizeCheckWeeks" type="number" min="1" max="26" value="${config.sizeCheckWeeks}" required><small>Wochen</small></div><div class="input-group"><label for="quietStart">Ruhezeit ab</label><input class="input" id="quietStart" name="quietStart" type="time" value="${esc(config.quietStart)}" required></div><div class="input-group"><label for="quietEnd">Ruhezeit bis</label><input class="input" id="quietEnd" name="quietEnd" type="time" value="${esc(config.quietEnd)}" required></div></div><div class="inline-note">Die Web-Testversion speichert diese Regeln lokal. Echte Push-Termine benötigen später die native Freigabe.</div><button class="btn primary block">Einstellungen speichern</button></form>`);}
  function nativeStatusModal(){const status=MyDiaper.platform.capabilities.status(),rows=[['Native Hülle',status.native],['Barcode-Scanner',status.barcode],['Kamera',status.camera],['Standort',status.location],['Benachrichtigungen',status.notifications],['Teilen',status.share]];modal('Gerätefunktionen',`<div class="capability-list">${rows.map(([label,ready])=>`<div class="settings-row"><span class="setting-symbol">${icon(ready?'check':'clock')}</span><span><strong>${label}</strong><small>${ready?'Auf diesem Gerät verfügbar':'Schnittstelle vorbereitet, Plugin/Freigabe noch offen'}</small></span></div>`).join('')}</div><div class="privacy-note">${icon('shield')}<span>Berechtigungen werden erst bei einer konkreten Funktion angefragt. Ort/PLZ bleibt manuell nutzbar.</span></div>`);}
  function legalStatusModal(){modal('Transparenz & Release-Status',`<div class="stack"><div class="card soft"><strong>Diese Testversion speichert lokal</strong><p>Kinderprofile, Windelsets, Vorräte, Erfahrungen, Einstellungen, Anzeigen und Chats bleiben im Browser bzw. im lokalen App-Speicher.</p></div><div class="card soft"><strong>Noch nicht produktiv</strong><p>Keine Konten, Cloud-Synchronisation, Zahlungen, Live-Händlerdaten oder serverseitige Moderation.</p></div><div class="card soft"><strong>Vor Veröffentlichung erforderlich</strong><p>Betreiberangaben, Datenschutz, Nutzungs- und Marktplatzregeln, Support-URLs, Store-Datenerklärungen sowie echte Moderations- und Löschwege.</p></div></div>`);}
  function newListingModal(existing){
    const item=existing||{mode:'Verkaufen',count:20,title:'',condition:'Original verschlossen',description:'',priceText:'',delivery:'Abholung',region:MyDiaper.store.get().settings.location,status:'active'};
    modal(existing?'Anzeige bearbeiten':'Anzeige aufgeben', `<form id="listingForm" class="stack" data-id="${esc(existing?.id||'')}"><div class="form-grid"><div class="input-group"><label for="listingMode">Art</label><select class="select" id="listingMode" name="mode">${['Verkaufen','Tauschen','Verschenken'].map(value=>`<option ${item.mode===value?'selected':''}>${value}</option>`).join('')}</select></div><div class="input-group"><label for="listingCount">Stückzahl</label><input class="input" id="listingCount" type="number" min="1" max="10000" name="count" value="${item.count}" required></div></div><div class="input-group"><label for="listingTitle">Titel</label><input class="input" id="listingTitle" name="title" maxlength="160" value="${esc(item.title)}" placeholder="z. B. Pampers Größe 4" required></div><div class="input-group"><label for="listingDescription">Beschreibung</label><textarea class="input" id="listingDescription" name="description" maxlength="1000">${esc(item.description||'')}</textarea></div><div class="form-grid"><div class="input-group"><label for="listingCondition">Zustand</label><select class="select" id="listingCondition" name="condition">${['Original verschlossen','Geöffnet · Restbestand'].map(value=>`<option ${item.condition===value?'selected':''}>${value}</option>`).join('')}</select></div><div class="input-group"><label for="listingDelivery">Übergabe</label><select class="select" id="listingDelivery" name="delivery">${['Abholung','Versand','Beides'].map(value=>`<option ${item.delivery===value?'selected':''}>${value}</option>`).join('')}</select></div><div class="input-group"><label for="listingPrice">Preis / Tauschwunsch</label><input class="input" id="listingPrice" name="price" maxlength="80" value="${esc(item.priceText)}" placeholder="z. B. 8 € / gegen Größe 5"></div><div class="input-group"><label for="listingRegion">Ort / Region</label><input class="input" id="listingRegion" name="region" maxlength="80" value="${esc(item.region)}" required></div></div><div class="privacy-note">${icon('shield')}<span>Lokale Demo: Die Anzeige ist nur auf diesem Gerät sichtbar.</span></div><button class="btn primary block">Anzeige speichern</button></form>`);
  }
  function marketSearchModal(){modal('Börse durchsuchen',`<form id="marketSearchForm" class="stack"><div class="input-group"><label for="marketQuery">Produkt, Größe, Person oder Region</label><input class="input" id="marketQuery" name="query" value="${esc(ui.marketQuery)}" placeholder="z. B. Größe 5"></div><button class="btn primary block">Suchen</button></form>`);}
  function reportListingModal(id){modal('Anzeige melden',`<form id="marketReportForm" class="stack" data-id="${esc(id)}"><div class="input-group"><label for="reportReason">Grund</label><select class="select" id="reportReason" name="reason"><option value="spam">Spam</option><option value="unsafe">Unsicheres Angebot</option><option value="misleading">Irreführende Angaben</option><option value="harassment">Belästigung</option><option value="other">Sonstiges</option></select></div><div class="input-group"><label for="reportNote">Hinweis (optional)</label><textarea class="input" id="reportNote" name="note" maxlength="500"></textarea></div><div class="inline-note">Die Meldung bleibt lokal. Eine echte Moderationsqueue benötigt das spätere Backend.</div><button class="btn primary block">Lokal markieren</button></form>`);}
  function manageBlocksModal(){const blocks=MyDiaper.marketplaceRepository.blocks();modal('Blockierte Kontakte',`<div class="history-list">${blocks.map(item=>`<article class="history-card"><span class="history-icon peach">${icon('shield')}</span><div><strong>${esc(item.owner)}</strong><p>Anzeigen und Nachrichten lokal ausgeblendet.</p></div><button class="text-btn" data-action="unblock-owner" data-id="${esc(item.ownerId)}">Freigeben</button></article>`).join('')||'<div class="friendly-empty compact"><strong>Keine Blockierungen</strong></div>'}</div>`);}
  function openChat(id){
    const item=MyDiaper.store.get().market.find(x=>x.id===id); const msgs=MyDiaper.marketplaceRepository.messages(id);
    modal(`Chat · ${item?item.owner:'Marktplatz'}`, `<div class="inline-note">${item?esc(item.title):''}</div><div class="chat-box">${msgs.length?msgs.map(m=>`<div class="chat-bubble ${m.from}">${esc(m.text)}</div>`).join(''):'<div class="empty">Noch keine Nachrichten.</div>'}</div><form id="chatForm" data-id="${id}" class="flex"><input class="input" name="message" placeholder="Nachricht schreiben …" required><button class="btn primary">Senden</button></form>`);
  }

  document.addEventListener('click', async (e)=>{
    try {
    if(e.target===modalRoot){if(modalDismissible)closeModal();return;}
    const b=e.target.closest('[data-action]'); if(!b) return; const a=b.dataset.action;
    if(a==='route'){ if(!closeModal())return; ui.route=b.dataset.route; render(); scrollTo({top:0,left:0,behavior:'instant'}); }
    if(a==='switch-child'){ if(!closeModal())return; repository.switchChild(b.dataset.id); render(); }
    if(a==='select-set'){ family.selectSet(b.dataset.id); render(); }
    if(a==='family-picker'){ modal('Deine Kinder',`<p class="child-picker-intro">Für wen schauen wir heute nach?</p>${childSwitcher()}<div class="child-picker-actions"><button class="btn primary" data-action="add-child">${icon('plus')} Kind hinzufügen</button><button class="btn secondary" data-action="edit-child">Profil bearbeiten</button></div>`); }
    if(a==='notifications') showNotifications();
    if(a==='tips') modal('Kleine Tipps für euren Alltag',`<div class="stack"><div class="card soft"><h3>Jedes Kind hat sein eigenes Set</h3><p>Wechsle über das Profilbild zwischen deinen Kindern. Vorräte und Fit-Checks bleiben getrennt.</p></div><div class="card soft"><h3>Alles im Blick</h3><p>Unter Windeln kannst du Packungen hinzufügen und den Verbrauch für Tages-, Nacht- oder Schwimmwindeln erfassen.</p></div><button class="btn primary" data-action="route" data-route="finder">Windel-Finder öffnen ${icon('arrow')}</button></div>`);
    if(a==='finder-choice'){MyDiaper.finder.choice(activeChild(),b.dataset.field,b.dataset.value);render();}
    if(a==='finder-next'){
      const d=MyDiaper.finder.state(activeChild());
      if(d.step===2){const input=document.getElementById('finderWeight');if(input && input.value!==undefined){const weight=Number(input.value);if(!Number.isFinite(weight)||weight<1||weight>80)throw new Error('Bitte ein Gewicht zwischen 1 und 80 kg eingeben.');d.weight=weight;}}
      d.step=Math.min(4,d.step+1);render();scrollTo({top:0,left:0,behavior:'instant'});
    }
    if(a==='finder-back'){const d=MyDiaper.finder.state(activeChild());d.step=Math.max(1,d.step-1);render();scrollTo({top:0,left:0,behavior:'instant'});}
    if(a==='finder-profile-check'){const d=MyDiaper.finder.state(activeChild());family.selectSet(d.setId);fitCheck();}
    if(a==='experience-add'){if(b.dataset.setId)family.selectSet(b.dataset.setId);experienceModal();}
    if(a==='experience-edit'){const c=activeChild(),experience=repository.listExperiences(c.id).find(item=>item.id===b.dataset.id&&item.setId===c.setId);if(!experience)throw new Error('Erfahrung für dieses Set nicht gefunden.');experienceModal(experience);}
    if(a==='experience-delete'&&confirm('Diese persönliche Produkterfahrung löschen?')){const form=b.closest('form');repository.deleteExperience(form.dataset.childId,form.dataset.setId,form.dataset.id);closeModal(true);toast('Produkterfahrung gelöscht.');render();}
    if(a==='history')historyModal();
    if(a==='catalog-assign'){const c=activeChild(),setId=b.dataset.setId||c.setId;repository.assignProduct(c.id,setId,b.dataset.id);family.selectSet(setId);toast('Katalogprodukt für dieses Set übernommen.');render();}
    if(a==='offer-view'){ui.offerView=b.dataset.view;render();}
    if(a==='map-store'){if(b.dataset.id==='unavailable')toast('Für diesen Händler sind keine Demo-Angebote hinterlegt.');else{ui.highlightOffer=b.dataset.id;render();}}
    if(a==='offer-search')modal('Angebote suchen',`<form id="offerSearchForm" class="stack"><div class="input-group"><label for="offerQuery">Produkt, Händler oder Größe</label><input class="input" id="offerQuery" name="query" value="${esc(ui.offerSearch||'')}" placeholder="z. B. Pampers"></div><button class="btn primary">Suchen</button></form>`);
    if(a==='favorite-offer'){MyDiaper.store.patch(s=>{const ids=s.settings.favoriteOfferIds||[];s.settings.favoriteOfferIds=ids.includes(b.dataset.id)?ids.filter(id=>id!==b.dataset.id):[...ids,b.dataset.id];});render();}
    if(a==='price-alert')priceAlertModal(MyDiaper.offerService.getById(b.dataset.id));
    if(a==='manage-alerts')manageAlertsModal();
    if(a==='remove-price-alert'){MyDiaper.offerRepository.removeAlert(activeChild().id,b.dataset.id);toast('Preisalarm entfernt.');manageAlertsModal();}
    if(a==='manage-offer-sources')offerSourcesModal();
    if(a==='remove-offer-source'&&confirm('Diese lokal importierte Angebotsquelle wirklich entfernen?')){MyDiaper.offerImportRepository.remove(b.dataset.id);toast('Angebotsquelle entfernt.');offerSourcesModal();render();}
    if(a==='reset-offer-imports'&&confirm('Die unlesbaren lokalen Angebotsimporte wirklich zurücksetzen?')){MyDiaper.offerImportRepository.reset();toast('Angebotsimporte zurückgesetzt.');offerSourcesModal();render();}
    if(a==='family-backup-export')backupExportModal();
    if(a==='family-backup-import')backupImportModal();
    if(a==='download-family-backup'){
      const day=new Date().toISOString().slice(0,10),text=MyDiaper.domain.backup.serialize(MyDiaper.store.get());
      if(MyDiaper.platform.files.downloadText(`mydiaper-familie-${day}.json`,text))toast('Familien-Backup heruntergeladen.');
      else toast('Download nicht verfügbar. Das JSON kann aus dem Textfeld kopiert werden.');
    }
    if(a==='add-child') childForm();
    if(a==='edit-child') childForm(activeChild());
    if(a==='edit-specific-child') childForm(MyDiaper.store.get().children.find(c=>c.id===b.dataset.id));
    if(a==='archive-child'&&confirm('Dieses Kinderprofil archivieren? Alle zugehörigen Daten bleiben erhalten.')){repository.archiveChild(b.dataset.id);family.clearSelection();toast('Kinderprofil archiviert.');render();}
    if(a==='restore-child'){repository.restoreChild(b.dataset.id);toast('Kinderprofil wiederhergestellt.');render();}
    if(a==='delete-child'&&confirm('Dieses archivierte Kinderprofil samt Sets, Vorräten und Verlauf endgültig löschen?')){repository.deleteChild(b.dataset.id);family.clearSelection();toast('Kinderprofil endgültig gelöscht.');render();}
    if(a==='fit-check') fitCheck();
    if(a==='edit-stock') stockModal();
    if(a==='add-stock') addStockModal();
    if(a==='manage-sets')manageSetsModal();
    if(a==='new-set')setFormModal();
    if(a==='edit-set'){const c=activeChild(),set=repository.listSets(c.id,true).find(item=>item.id===b.dataset.id);if(!set)throw new Error('Windelset nicht gefunden.');setFormModal(set);}
    if(a==='set-primary'){const c=activeChild();repository.setPrimary(c.id,b.dataset.id);family.selectSet(b.dataset.id);toast('Hauptset geändert.');manageSetsModal();render();}
    if(a==='toggle-set'){const c=activeChild();if(b.dataset.active==='true')repository.deactivateSet(c.id,b.dataset.id);else repository.reactivateSet(c.id,b.dataset.id);family.clearSelection();toast(b.dataset.active==='true'?'Windelset pausiert.':'Windelset aktiviert.');manageSetsModal();render();}
    if(a==='delete-set'&&confirm('Dieses Windelset samt Vorräten und Verlauf endgültig löschen?')){const c=activeChild();repository.deleteSet(c.id,b.dataset.id);family.clearSelection();toast('Windelset gelöscht.');manageSetsModal();render();}
    if(a==='manage-lots')manageLotsModal();
    if(a==='edit-lot'){const c=activeChild(),lot=repository.listLots(c.id,c.setId).find(item=>item.id===b.dataset.id);if(!lot)throw new Error('Vorratsposten nicht gefunden.');lotFormModal(lot);}
    if(a==='delete-lot'&&confirm('Diesen Vorratsposten endgültig löschen?')){const c=activeChild();repository.removeLot(c.id,c.setId,b.dataset.id);toast('Vorratsposten gelöscht.');manageLotsModal();render();}
    if(a==='barcode-entry')barcodeModal();
    if(a==='barcode-scan'){const value=await MyDiaper.platform.capabilities.scanBarcode();if(value)barcodeResult(value);}
    if(a==='catalog-corrections')correctionsModal();
    if(a==='delete-correction'){MyDiaper.catalogCorrectionRepository.remove(b.dataset.id);toast('Korrekturentwurf gelöscht.');correctionsModal();render();}
    if(a==='reminder-settings')reminderSettingsModal();
    if(a==='native-status')nativeStatusModal();
    if(a==='legal-status')legalStatusModal();
    if(a==='use-one')activityForm();
    if(a==='offer-tab'){ ui.offerMode=b.dataset.mode; render(); }
    if(a==='market-tab'){ ui.marketFilter=b.dataset.mode; render(); }
    if(a==='market-mine'){ui.marketOnlyMine=!ui.marketOnlyMine;render();}
    if(a==='market-search')marketSearchModal();
    if(a==='new-listing') newListingModal();
    if(a==='edit-listing'){const item=MyDiaper.store.get().market.find(entry=>entry.id===b.dataset.id);if(!item)throw new Error('Anzeige nicht gefunden.');newListingModal(item);}
    if(a==='listing-status'){MyDiaper.marketplaceRepository.setStatus(b.dataset.id,b.dataset.status);toast('Anzeigenstatus aktualisiert.');render();}
    if(a==='delete-listing'&&confirm('Eigene Anzeige endgültig löschen?')){MyDiaper.marketplaceRepository.remove(b.dataset.id);toast('Anzeige gelöscht.');render();}
    if(a==='report-listing')reportListingModal(b.dataset.id);
    if(a==='block-owner'&&confirm('Diesen Kontakt lokal blockieren und seine Anzeigen ausblenden?')){MyDiaper.marketplaceRepository.block(b.dataset.id);toast('Kontakt lokal blockiert.');render();}
    if(a==='manage-blocks')manageBlocksModal();
    if(a==='unblock-owner'){MyDiaper.marketplaceRepository.unblock(b.dataset.id);toast('Kontakt wieder freigegeben.');manageBlocksModal();render();}
    if(a==='open-chat') openChat(b.dataset.id);
    if(a==='edit-location') locationModal();
    if(a==='use-current-location'){b.disabled=true;b.textContent='Standort wird ermittelt …';ui.mapLocation=await MyDiaper.platform.location.current();closeModal(true);ui.route='offers';ui.offerMode='local';ui.offerView='map';render();toast('Standort nur für diese Kartenansicht verwendet.');}
    if(a==='salutation-settings')salutationModal();
    if(a==='activity-add')activityForm();
    if(a==='activity-log')activityModal();
    if(a==='activity-edit'){const event=repository.listUsage(activeChild().id).find(item=>item.id===b.dataset.id);if(event)activityForm(event);}
    if(a==='activity-undo'&&confirm('Diesen Windelwechsel rückgängig machen und die Windel wieder zum Vorrat legen?')){repository.undoUsage(activeChild().id,b.dataset.id);toast('Windelwechsel rückgängig gemacht.');activityModal();render();}
    if(a==='activity-range'){ui.activityRange=b.dataset.range;activityModal();}
    if(a==='close-modal') closeModal();
    if(a==='reset-app' && confirm('Testdaten wirklich zurücksetzen?')){ MyDiaper.store.reset(); family.clearSelection(); MyDiaper.finder.reset(); toast('Testdaten zurückgesetzt.'); render(); }
    } catch(error) { toast(error.message); }
  });

  document.addEventListener('change', async (e)=>{
    try {
    if(MyDiaper.productFields?.change(e.target)){
      if(e.target.matches('[data-product-package]')){const form=e.target.closest('form'),value=MyDiaper.productFields.value(form);if(value?.packageUnits)form.querySelector('[name="amount"]').value=value.packageUnits;}
    }
    if(e.target.id==='setLabel')MyDiaper.productFields?.purpose(e.target.form.querySelector('[data-product-picker]'),MyDiaper.domain.model.purpose(e.target.value));
    if(e.target.id==='offerImportFile'&&e.target.files?.[0]){document.getElementById('offerImportBundle').value=await MyDiaper.platform.files.readText(e.target.files[0],MyDiaper.domain.offers.MAX_IMPORT_CHARS);toast('Angebotsdatei geladen. Bitte Import bestätigen.');}
    if(e.target.id==='familyBackupFile'&&e.target.files?.[0]){document.getElementById('familyBackupText').value=await MyDiaper.platform.files.readText(e.target.files[0],MyDiaper.domain.backup.MAX_CHARS);toast('Backup-Datei geladen. Bitte Einlesen bestätigen.');}
    if(e.target.matches('[data-setting]')){ const key=e.target.dataset.setting; MyDiaper.store.patch(s=>s.settings.reminders[key]=e.target.checked); toast('Einstellung gespeichert.'); }
    } catch(error) { toast(error.message); render(); }
  });
  document.addEventListener('input',e=>{if(e.target.matches('[data-product-search]'))MyDiaper.productFields?.change(e.target);if(e.target.id==='maxPackPrice'){const hint=e.target.nextElementSibling,match=hint?.textContent.match(/(\d+) Stück/),count=Number(match?.[1]),price=Number(e.target.value);if(hint&&count)hint.textContent=Number.isFinite(price)&&price>0?`Gilt exakt für ${count} Stück · entspricht ${(price/count).toFixed(2).replace('.',',')} € pro Windel.`:`Gilt exakt für ${count} Stück.`;}});

  document.addEventListener('submit',(e)=>{
    try {
    if(e.target.id==='finderWeightForm'){e.preventDefault();const weight=Number(new FormData(e.target).get('weight'));if(!Number.isFinite(weight)||weight<1||weight>80)throw new Error('Bitte ein Gewicht zwischen 1 und 80 kg eingeben.');MyDiaper.finder.state(activeChild()).weight=weight;toast('Gewicht für den Finder übernommen.');}
    if(e.target.id==='offerSearchForm'){e.preventDefault();ui.offerSearch=String(new FormData(e.target).get('query')||'');ui.offerView='list';closeModal(true);render();}
    if(e.target.id==='childForm'){
      e.preventDefault(); const f=new FormData(e.target);
      repository.saveChildProfile({id:e.target.dataset.id || undefined,name:f.get('name'),birthdate:f.get('birthdate'),weight:+f.get('weight'),height:+f.get('height'),color:f.get('color'),brand:f.get('brand'),size:f.get('size'),dailyUse:+f.get('dailyUse'),stock:+f.get('stock'),types:String(f.get('types')).split(',')});
      closeModal(true); toast('Kinderprofil gespeichert.'); render();
    }
    if(e.target.id==='fitForm'){
      e.preventDefault(); const f=new FormData(e.target);
      repository.saveFitCheck(e.target.dataset.childId,e.target.dataset.setId,Object.fromEntries(f));
      closeModal(true); toast('Fit-Check gespeichert.'); render();
    }
    if(e.target.id==='experienceForm'){
      e.preventDefault();const f=new FormData(e.target);
      repository.saveExperience(e.target.dataset.childId,e.target.dataset.setId,{id:e.target.dataset.id||undefined,fitRating:+f.get('fitRating'),leakRating:+f.get('leakRating'),nightRating:+f.get('nightRating'),skinComfortRating:+f.get('skinComfortRating'),priceValueRating:f.get('priceValueRating')===null?undefined:+f.get('priceValueRating'),wouldBuyAgain:f.get('wouldBuyAgain')===null?null:f.get('wouldBuyAgain')==='yes',sizeTendency:f.get('sizeTendency'),avoidRecommendation:f.get('avoidRecommendation')!==null,notes:f.get('notes')||''});
      closeModal(true);toast('Persönliche Erfahrung gespeichert.');render();
    }
    if(e.target.id==='stockForm') { e.preventDefault(); const f=new FormData(e.target),product=productValue(e.target,f); repository.updateSet(e.target.dataset.childId,e.target.dataset.setId,{...product,stock:+f.get('stock'),dailyUse:+f.get('dailyUse')}); closeModal(true); toast('Vorrat aktualisiert.'); render(); }
    if(e.target.id==='addStockForm') { e.preventDefault(); const f=new FormData(e.target),product=productValue(e.target,f),amount=product.packageUnits||+f.get('amount'); repository.addStock(e.target.dataset.childId,e.target.dataset.setId,amount,{productSizeId:product.productSizeId,productPackageId:product.productPackageId,productSnapshot:{brand:product.brand,line:product.line,size:product.size},storageLocation:f.get('storageLocation')||'Zuhause',acquiredAt:f.get('acquiredAt'),note:f.get('note')}); closeModal(true); toast('Vorrat ergänzt.'); render(); }
    if(e.target.id==='setForm'){e.preventDefault();const f=new FormData(e.target),childId=e.target.dataset.childId,product=productValue(e.target,f),input={label:f.get('label'),...product,dailyUse:+f.get('dailyUse')};if(e.target.dataset.id)repository.updateSet(childId,e.target.dataset.id,input);else repository.createSet(childId,{...input,stock:+f.get('stock')});family.clearSelection();closeModal(true);toast('Windelset gespeichert.');render();}
    if(e.target.id==='lotForm'){e.preventDefault();const f=new FormData(e.target);repository.updateLot(e.target.dataset.childId,e.target.dataset.setId,e.target.dataset.id,{initialUnits:+f.get('initialUnits'),remainingUnits:+f.get('remainingUnits'),storageLocation:f.get('storageLocation'),acquiredAt:f.get('acquiredAt'),note:f.get('note')});closeModal(true);toast('Vorratsposten gespeichert.');render();}
    if(e.target.id==='barcodeForm'){e.preventDefault();const f=new FormData(e.target);barcodeResult(f.get('barcode'));}
    if(e.target.id==='correctionForm'){e.preventDefault();const f=new FormData(e.target);MyDiaper.catalogCorrectionRepository.save({barcode:e.target.dataset.barcode,kind:f.get('kind'),note:f.get('note')});closeModal(true);toast('Lokaler Korrekturentwurf gespeichert.');render();}
    if(e.target.id==='barcodeStockForm'){e.preventDefault();repository.assignProduct(e.target.dataset.childId,e.target.dataset.setId,e.target.dataset.productSizeId);repository.addStock(e.target.dataset.childId,e.target.dataset.setId,+e.target.dataset.units,{productSizeId:e.target.dataset.productSizeId,storageLocation:'Zuhause',note:'Per Barcode erfasst'});closeModal(true);toast('Produkt und Vorrat übernommen.');render();}
    if(e.target.id==='reminderForm'){e.preventDefault();const f=new FormData(e.target),config=MyDiaper.domain.reminders.normalize({stockDays:+f.get('stockDays'),sizeCheckWeeks:+f.get('sizeCheckWeeks'),quietStart:f.get('quietStart'),quietEnd:f.get('quietEnd')});MyDiaper.store.patch(state=>state.settings.reminderConfig=config);closeModal(true);toast('Erinnerungen gespeichert.');render();}
    if(e.target.id==='locationForm') { e.preventDefault(); const f=new FormData(e.target); MyDiaper.store.patch(s=>{s.settings.location=f.get('location');s.settings.locationMode='manual';}); ui.mapLocation=null;closeModal(true); toast('Standort gespeichert.'); render(); }
    if(e.target.id==='priceAlertForm'){e.preventDefault();const f=new FormData(e.target),unit=f.get('maxUnitPrice'),pack=f.get('maxPackPrice');MyDiaper.offerRepository.saveAlert(e.target.dataset.childId,{id:e.target.dataset.id||undefined,productSizeId:e.target.dataset.productSizeId,productPackageId:pack?e.target.dataset.productPackageId:null,maxUnitPrice:unit||null,maxPackPrice:pack||null,scope:f.get('scope'),enabled:true});closeModal(true);toast('Preisalarm gespeichert.');render();}
    if(e.target.id==='salutationForm'){e.preventDefault();const f=new FormData(e.target);repository.saveSalutation({choice:f.get('choice'),customName:f.get('customName')});closeModal(true);toast('Begrüßung gespeichert.');render();}
    if(e.target.id==='activityForm'){e.preventDefault();const f=new FormData(e.target),input={contents:f.get('contents'),usedAt:f.get('usedAt'),note:f.get('note')};if(e.target.dataset.id)repository.updateUsage(e.target.dataset.childId,e.target.dataset.id,input);else if(!repository.recordUsage(e.target.dataset.childId,f.get('setId'),input))throw new Error('Kein Vorrat zum Abziehen vorhanden.');closeModal(true);toast(e.target.dataset.id?'Windelwechsel aktualisiert.':'Windelwechsel gespeichert.');render();}
    if(e.target.id==='offerImportForm'){e.preventDefault();const f=new FormData(e.target),result=MyDiaper.offerImportRepository.importText(f.get('bundle'));ui.offerView='list';closeModal(true);toast(`${result.offerCount} Angebot${result.offerCount===1?'':'e'} aus ${result.label} importiert.`);render();}
    if(e.target.id==='backupImportForm'){
      e.preventDefault();const f=new FormData(e.target),backup=MyDiaper.domain.backup.parse(String(f.get('backup')||''));
      if(!confirm('Das geprüfte Backup ersetzt jetzt die lokal gespeicherten Familien- und Einstellungsdaten. Fortfahren?'))return;
      MyDiaper.store.replace(backup.state);family.clearSelection();MyDiaper.finder.reset();closeModal(true);toast('Familien-Backup erfolgreich eingelesen.');render();
    }
    if(e.target.id==='marketSearchForm'){e.preventDefault();ui.marketQuery=String(new FormData(e.target).get('query')||'').trim();closeModal(true);render();}
    if(e.target.id==='marketReportForm'){e.preventDefault();const f=new FormData(e.target);MyDiaper.marketplaceRepository.report(e.target.dataset.id,{reason:f.get('reason'),note:f.get('note')});closeModal(true);toast('Anzeige lokal markiert.');render();}
    if(e.target.id==='listingForm') { e.preventDefault(); const f=new FormData(e.target);MyDiaper.marketplaceRepository.save({id:e.target.dataset.id||undefined,mode:f.get('mode'),title:f.get('title'),description:f.get('description'),condition:f.get('condition'),count:+f.get('count'),priceText:f.get('price')||undefined,delivery:f.get('delivery'),region:f.get('region')}); closeModal(true); toast('Anzeige lokal gespeichert.'); render(); }
    if(e.target.id==='chatForm') { e.preventDefault(); const f=new FormData(e.target); const id=e.target.dataset.id;MyDiaper.marketplaceRepository.send(id,f.get('message'));openChat(id); }
    } catch(error) { toast(error.message); }
  });

  document.querySelectorAll('.nav-item').forEach(b=>{
    const entry=({today:['home','Heute'],diapers:['diaper','Windeln'],offers:['tag','Angebote'],market:['swap','Börse'],profile:['user','Profil']})[b.dataset.route];
    b.innerHTML=icon(entry[0],entry[0])+`<small>${entry[1]}</small>`;
    b.addEventListener('click',()=>{if(!closeModal())return;ui.route=b.dataset.route;render();scrollTo({top:0,left:0,behavior:'instant'});});
  });
  document.getElementById('notificationsButton').addEventListener('click',showNotifications);
  document.getElementById('desktopBrand').innerHTML=art('brandElephant')+art('wordmark')+'<p>Kleine Schritte. Große Abenteuer.</p><p class="handwritten">Mehr Zeit für das,<br>was wirklich zählt. ♡</p>';

  window.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalDismissible)closeModal();});
  render();
  let lastBackAt=0;
  MyDiaper.platform.navigation?.register(()=>{
    if(isModalOpen()){if(modalDismissible)closeModal();return;}
    if(ui.route==='finder'){const draft=MyDiaper.finder.state(activeChild());if(draft.step>1){draft.step-=1;render();return;}ui.route='today';render();return;}
    if(ui.route!=='today'){ui.route='today';render();scrollTo({top:0,left:0,behavior:'instant'});return;}
    const current=Date.now();if(current-lastBackAt<=2000)MyDiaper.platform.navigation.exit();else{lastBackAt=current;toast('Zum Beenden erneut Zurück drücken.');}
  });
  if(!MyDiaper.store.get().settings.salutation.completed)setTimeout(()=>salutationModal(true),0);
  if(MyDiaper.store.status().warning) toast(MyDiaper.store.status().warning);

  if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
