(function(){
  'use strict';
  MyDiaper.features=MyDiaper.features||{};
  MyDiaper.features.market=function(ctx){
    const filter=ctx.ui.marketFilter||'Alle',query=ctx.ui.marketQuery||'',onlyMine=Boolean(ctx.ui.marketOnlyMine);
    const items=MyDiaper.marketplaceRepository.list({mode:filter,query,onlyMine}),blocks=MyDiaper.marketplaceRepository.blocks();
    const iconFor=mode=>mode==='Verschenken'?'heart':mode==='Tauschen'?'swap':'tag';
    return `<div class="market-screen">${ctx.screenHeader('Windel-Börse')}
      <section class="market-hero"><div><p class="eyebrow">Weitergeben statt wegwerfen</p><h1>Windeln finden<br>ein neues Zuhause.</h1><p>Verkaufen, tauschen, verschenken – als lokale, sichere Testfunktion.</p></div><span class="market-hero-art">${ctx.icon('swap')}</span></section>
      <div class="market-filter" aria-label="Anzeigen filtern">${['Alle','Verkaufen','Tauschen','Verschenken'].map(mode=>`<button class="${filter===mode?'selected':''}" data-action="market-tab" data-mode="${mode}" aria-pressed="${filter===mode}">${mode}</button>`).join('')}</div>
      <div class="market-tools"><button class="btn secondary" data-action="market-search">${ctx.icon('search')} ${query?`„${ctx.esc(query)}“`:'Suchen'}</button><button class="btn secondary ${onlyMine?'selected':''}" data-action="market-mine" aria-pressed="${onlyMine}">${ctx.icon('user')} Meine Anzeigen</button></div>
      <button class="btn primary block create-listing" data-action="new-listing">${ctx.icon('plus')} Anzeige aufgeben</button>
      <section class="market-results"><div class="section-heading"><h2>${onlyMine?'Meine Anzeigen':filter==='Alle'?'Anzeigen in deiner Nähe':filter}</h2><span>${items.length} Treffer</span></div>
        ${items.map(item=>`<article class="market-card" data-listing-id="${ctx.esc(item.id)}"><div class="listing-icon ${item.mode.toLowerCase()}">${ctx.icon(iconFor(item.mode))}</div><div class="listing-body"><div class="listing-top"><span class="listing-mode">${ctx.esc(item.mode)}</span><small>${ctx.esc(item.status==='reserved'?'Reserviert':item.status==='completed'?'Abgeschlossen':item.createdAt?'Neu':'Demo')}</small></div><h3>${ctx.esc(item.title)}</h3><p>${ctx.esc(item.condition)} · ${item.count} Stück</p><div class="listing-meta"><span>${ctx.icon('pin')} ${ctx.esc(item.region)} · ${ctx.esc(item.delivery)}</span><strong>${ctx.esc(item.priceText)}</strong></div><div class="listing-owner"><span class="mini-avatar">${ctx.esc(item.owner.slice(0,1))}</span><span>von ${ctx.esc(item.owner)}</span><button class="text-btn" data-action="open-chat" data-id="${ctx.esc(item.id)}">Chat öffnen ${ctx.icon('arrow')}</button></div>${item.ownerId==='local-user'?`<div class="listing-actions"><button class="text-btn" data-action="edit-listing" data-id="${ctx.esc(item.id)}">Bearbeiten</button><button class="text-btn" data-action="listing-status" data-id="${ctx.esc(item.id)}" data-status="${item.status==='active'?'reserved':'active'}">${item.status==='active'?'Reservieren':'Aktivieren'}</button><button class="text-btn danger-text" data-action="delete-listing" data-id="${ctx.esc(item.id)}">Löschen</button></div>`:`<div class="listing-actions"><button class="text-btn" data-action="report-listing" data-id="${ctx.esc(item.id)}">Melden</button><button class="text-btn" data-action="block-owner" data-id="${ctx.esc(item.id)}">Kontakt blockieren</button></div>`}</div></article>`).join('')||`<div class="friendly-empty">${ctx.art('elephant')}<h2>Hier ist es noch ganz ruhig.</h2><p>Suche oder Filter ändern – oder eine eigene Demo-Anzeige erstellen.</p></div>`}
      </section>${blocks.length?`<button class="reset-link" data-action="manage-blocks">${blocks.length} blockierte Kontakte verwalten</button>`:''}<p class="market-notice">Lokale Demo · Keine öffentlichen Konten, Zahlungen oder serverseitige Moderation.</p></div>`;
  };
})();
