window.MyDiaper=window.MyDiaper||{};MyDiaper.features=MyDiaper.features||{};

MyDiaper.features.profile=function(ctx){
  const state=MyDiaper.store.get(),children=state.children.map(child=>ctx.childView(child.id));
  const reminders={stock:['box','Vorrat wird knapp'],size:['diaper','Möglicher Größenwechsel'],offers:['tag','Passende Angebote'],market:['bell','Marktplatz-Nachrichten']};
  return `<div class="profile-screen">${ctx.screenHeader('Profil')}
    <section class="profile-hero"><div><p class="eyebrow">Eure Familie</p><h1>Alles Persönliche<br>an einem Ort.</h1><p>Familie, Erinnerungen & App – lokal und nach Kindern getrennt.</p></div>${ctx.art('elephant')}</section>
    <section class="profile-section"><div class="section-heading"><h2>Kinderprofile</h2><button class="text-btn" data-action="add-child">${ctx.icon('plus')} Kind hinzufügen</button></div><div class="profile-children">${children.map(child=>`<article class="profile-child ${child.id===state.activeChildId?'active':''}"><button class="child-main" data-action="switch-child" data-id="${ctx.esc(child.id)}" aria-label="${ctx.esc(child.name)} auswählen"><span class="avatar ${ctx.esc(child.color)}">${ctx.esc(child.name.slice(0,1).toUpperCase())}</span><span><strong>${ctx.esc(child.name)}</strong><small>${child.weight.toFixed(1).replace('.',',')} kg · ${child.height} cm · Größe ${ctx.esc(child.currentSize)}</small></span></button><button class="icon-btn" data-action="edit-specific-child" data-id="${ctx.esc(child.id)}" aria-label="${ctx.esc(child.name)} bearbeiten">${ctx.icon('user')}</button></article>`).join('')}</div></section>
    <section class="profile-section"><h2>Erinnerungen</h2><div class="settings-card">${Object.entries(reminders).map(([key,[symbol,label]])=>`<label class="settings-row"><span class="setting-symbol">${ctx.icon(symbol)}</span><span>${label}<small>Für wichtige Hinweise in MyDiaper</small></span><input class="toggle" type="checkbox" data-setting="${key}" aria-label="${label}" ${state.settings.reminders[key]?'checked':''}></label>`).join('')}</div></section>
    <section class="profile-section"><h2>Standort & Geschäfte</h2><div class="settings-card"><div class="settings-row"><span class="setting-symbol">${ctx.icon('pin')}</span><span><strong>${ctx.esc(state.settings.location)}</strong><small>manuell gewählt · kein Standortzwang</small></span><button class="text-btn" data-action="edit-location">Ändern</button></div><div class="settings-row"><span class="setting-symbol">${ctx.icon('heart')}</span><span><strong>Lieblingsgeschäfte</strong><small>${ctx.esc(state.settings.preferredStores.join(', '))}</small></span></div></div></section>
    <section class="profile-section"><h2>Daten & Synchronisation</h2><div class="settings-card"><div class="settings-row"><span class="setting-symbol">${ctx.icon('box')}</span><span><strong>Lokales Familien-Backup</strong><small>Versioniertes JSON für eine spätere Synchronisation</small></span><button class="text-btn" data-action="family-backup-export">Exportieren</button></div><div class="settings-row"><span class="setting-symbol">${ctx.icon('swap')}</span><span><strong>Backup wieder einlesen</strong><small>Vor dem Ersetzen werden alle Daten geprüft</small></span><button class="text-btn" data-action="family-backup-import">Importieren</button></div></div><p class="profile-data-note">Noch kein Konto und keine Cloud: Die Dateien bleiben unter deiner Kontrolle auf diesem Gerät.</p></section>
    <section class="about-card"><span class="about-elephant">${ctx.art('brandElephant')}</span><div><strong>MyDiaper Testversion 1.0</strong><p>Profile und Einstellungen werden lokal im Browser gespeichert.</p><small>Idee: Felix & Christoph<br>Konzept, Aufbau & Code: Christoph · christoph-it</small></div></section>
    <button class="reset-link" data-action="reset-app">Testdaten zurücksetzen</button></div>`;
};
