(function(){
  'use strict';
  MyDiaper.features=MyDiaper.features||{};
  MyDiaper.features.profile=function(ctx){
    const state=MyDiaper.store.get(),children=MyDiaper.repository.listChildren().map(child=>ctx.childView(child.id)),archived=MyDiaper.repository.listChildren(true).filter(child=>child.archivedAt).map(child=>ctx.childView(child.id));
    const reminders={stock:['box','Vorrat wird knapp'],size:['diaper','Möglicher Größenwechsel'],offers:['tag','Passende Angebote'],market:['bell','Marktplatz-Nachrichten']};
    const native=MyDiaper.platform.capabilities.status(),corrections=MyDiaper.catalogCorrectionRepository.list();
    const childCard=(child,isArchived=false)=>`<article class="profile-child ${child.id===state.activeChildId?'active':''} ${isArchived?'archived':''}"><button class="child-main" ${isArchived?'disabled':`data-action="switch-child" data-id="${ctx.esc(child.id)}"`} aria-label="${ctx.esc(child.name)} ${isArchived?'archiviert':'auswählen'}"><span class="avatar ${ctx.esc(child.color)}">${ctx.esc(child.name.slice(0,1).toUpperCase())}</span><span><strong>${ctx.esc(child.name)}</strong><small>${child.weight.toFixed(1).replace('.',',')} kg · ${child.height} cm · Größe ${ctx.esc(child.currentSize)}</small></span></button><div class="profile-child-actions">${isArchived?`<button class="icon-btn" data-action="restore-child" data-id="${ctx.esc(child.id)}" aria-label="${ctx.esc(child.name)} wiederherstellen">${ctx.icon('swap')}</button><button class="icon-btn" data-action="delete-child" data-id="${ctx.esc(child.id)}" aria-label="${ctx.esc(child.name)} endgültig löschen">${ctx.icon('close')}</button>`:`<button class="icon-btn" data-action="edit-specific-child" data-id="${ctx.esc(child.id)}" aria-label="${ctx.esc(child.name)} bearbeiten">${ctx.icon('user')}</button><button class="icon-btn" data-action="archive-child" data-id="${ctx.esc(child.id)}" aria-label="${ctx.esc(child.name)} archivieren">${ctx.icon('box')}</button>`}</div></article>`;
    return `<div class="profile-screen">${ctx.screenHeader('Profil')}
      <section class="profile-hero"><div><p class="eyebrow">Eure Familie</p><h1>Alles Persönliche<br>an einem Ort.</h1><p>Familie, Erinnerungen & App – lokal und nach Kindern getrennt.</p></div>${ctx.art('elephant')}</section>
      <section class="profile-section"><div class="section-heading"><h2>Kinderprofile</h2><button class="text-btn" data-action="add-child">${ctx.icon('plus')} Kind hinzufügen</button></div><div class="profile-children">${children.map(child=>childCard(child)).join('')}</div>${archived.length?`<details class="archive-panel"><summary>Archivierte Kinder (${archived.length})</summary><div class="profile-children">${archived.map(child=>childCard(child,true)).join('')}</div></details>`:''}</section>
      <section class="profile-section"><div class="section-heading"><h2>Erinnerungen</h2><button class="text-btn" data-action="reminder-settings">Fein einstellen</button></div><div class="settings-card">${Object.entries(reminders).map(([key,[symbol,label]])=>`<label class="settings-row"><span class="setting-symbol">${ctx.icon(symbol)}</span><span>${label}<small>Für wichtige Hinweise in MyDiaper</small></span><input class="toggle" type="checkbox" data-setting="${key}" aria-label="${label}" ${state.settings.reminders[key]?'checked':''}></label>`).join('')}</div><p class="profile-data-note">Warnung ab ${state.settings.reminderConfig.stockDays} Tagen Vorrat · Größencheck alle ${state.settings.reminderConfig.sizeCheckWeeks} Wochen.</p></section>
      <section class="profile-section"><h2>Standort & Geschäfte</h2><div class="settings-card"><div class="settings-row"><span class="setting-symbol">${ctx.icon('pin')}</span><span><strong>${ctx.esc(state.settings.location)}</strong><small>manuell gewählt · kein Standortzwang</small></span><button class="text-btn" data-action="edit-location">Ändern</button></div><div class="settings-row"><span class="setting-symbol">${ctx.icon('heart')}</span><span><strong>Lieblingsgeschäfte</strong><small>${ctx.esc(state.settings.preferredStores.join(', '))}</small></span></div></div></section>
      <section class="profile-section"><h2>Produkte & Gerätefunktionen</h2><div class="settings-card"><div class="settings-row"><span class="setting-symbol">${ctx.icon('search')}</span><span><strong>Barcode & Produktkorrekturen</strong><small>${corrections.length} lokale${corrections.length===1?'r':''} Entwurf${corrections.length===1?'':'e'}</small></span><button class="text-btn" data-action="catalog-corrections">Öffnen</button></div><div class="settings-row"><span class="setting-symbol">${ctx.icon('shield')}</span><span><strong>${native.native?'Native App erkannt':'Web-Testversion'}</strong><small>Scanner, Kamera, Standort und Push bleiben opt-in</small></span><button class="text-btn" data-action="native-status">Status</button></div></div></section>
      <section class="profile-section"><h2>Daten & Synchronisation</h2><div class="settings-card"><div class="settings-row"><span class="setting-symbol">${ctx.icon('box')}</span><span><strong>Lokales Familien-Backup</strong><small>Versioniertes JSON für eine spätere Synchronisation</small></span><button class="text-btn" data-action="family-backup-export">Exportieren</button></div><div class="settings-row"><span class="setting-symbol">${ctx.icon('swap')}</span><span><strong>Backup wieder einlesen</strong><small>Vor dem Ersetzen werden alle Daten geprüft</small></span><button class="text-btn" data-action="family-backup-import">Importieren</button></div></div><p class="profile-data-note">Noch kein Konto und keine Cloud: Die Dateien bleiben unter deiner Kontrolle auf diesem Gerät.</p></section>
      <section class="profile-section"><h2>Rechtliches & Release</h2><div class="settings-card"><div class="settings-row"><span class="setting-symbol">${ctx.icon('shield')}</span><span><strong>Transparenz der Testversion</strong><small>Lokale Daten, Demo-Angebote und offene Release-Gates</small></span><button class="text-btn" data-action="legal-status">Ansehen</button></div></div></section>
      <section class="about-card"><span class="about-elephant">${ctx.art('brandElephant')}</span><div><strong>MyDiaper Testversion 1.1.2</strong><p>Profile und Einstellungen werden lokal im Browser gespeichert.</p><small>Idee: Felix & Christoph<br>Konzept, Aufbau & Code: Christoph · christoph-it</small></div></section>
      <button class="reset-link" data-action="reset-app">Testdaten zurücksetzen</button></div>`;
  };
})();
